cmake_minimum_required(VERSION 3.23)
project(kk_transfrmr LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
find_package(Kokkos REQUIRED)
find_package(KokkosFFT REQUIRED)
add_executable(sol electro_static_potential_48_61.cpp)
target_link_libraries(sol PRIVATE Kokkos::kokkos KokkosFFT::fft)
if(NOT CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE release)
endif()
