cmake_minimum_required(VERSION 3.23)
project(mine LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
if (NOT CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE Release)
endif()
find_package(Kokkos REQUIRED)
find_package(KokkosFFT REQUIRED)
add_executable(hfft hfft_hermitian_pulse.cpp)
target_link_libraries(hfft PRIVATE Kokkos::kokkos KokkosFFT::fft)
